// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.8
// source: sub_msg.proto

package sub_message

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetSubMessageReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SubMessage string `protobuf:"bytes,1,opt,name=subMessage,proto3" json:"subMessage,omitempty"`
}

func (x *GetSubMessageReq) Reset() {
	*x = GetSubMessageReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sub_msg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSubMessageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubMessageReq) ProtoMessage() {}

func (x *GetSubMessageReq) ProtoReflect() protoreflect.Message {
	mi := &file_sub_msg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubMessageReq.ProtoReflect.Descriptor instead.
func (*GetSubMessageReq) Descriptor() ([]byte, []int) {
	return file_sub_msg_proto_rawDescGZIP(), []int{0}
}

func (x *GetSubMessageReq) GetSubMessage() string {
	if x != nil {
		return x.SubMessage
	}
	return ""
}

type GetSubMessageReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MessageReply string `protobuf:"bytes,1,opt,name=messageReply,proto3" json:"messageReply,omitempty"`
}

func (x *GetSubMessageReply) Reset() {
	*x = GetSubMessageReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sub_msg_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSubMessageReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubMessageReply) ProtoMessage() {}

func (x *GetSubMessageReply) ProtoReflect() protoreflect.Message {
	mi := &file_sub_msg_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubMessageReply.ProtoReflect.Descriptor instead.
func (*GetSubMessageReply) Descriptor() ([]byte, []int) {
	return file_sub_msg_proto_rawDescGZIP(), []int{1}
}

func (x *GetSubMessageReply) GetMessageReply() string {
	if x != nil {
		return x.MessageReply
	}
	return ""
}

var File_sub_msg_proto protoreflect.FileDescriptor

var file_sub_msg_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x73, 0x75, 0x62, 0x5f, 0x6d, 0x73, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x11, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x75, 0x62, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e,
	0x76, 0x31, 0x22, 0x32, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x53, 0x75, 0x62, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x75, 0x62, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x75, 0x62, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x38, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x53, 0x75, 0x62,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x22, 0x0a, 0x0c,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0c, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x32, 0x75, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x53, 0x75, 0x62, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x5d, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x53,
	0x75, 0x62, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x23, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x73, 0x75, 0x62, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65,
	0x74, 0x53, 0x75, 0x62, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x25,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x75, 0x62, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e,
	0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x75, 0x62, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x10, 0x5a, 0x0e, 0x2e, 0x2f, 0x3b, 0x73, 0x75,
	0x62, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_sub_msg_proto_rawDescOnce sync.Once
	file_sub_msg_proto_rawDescData = file_sub_msg_proto_rawDesc
)

func file_sub_msg_proto_rawDescGZIP() []byte {
	file_sub_msg_proto_rawDescOnce.Do(func() {
		file_sub_msg_proto_rawDescData = protoimpl.X.CompressGZIP(file_sub_msg_proto_rawDescData)
	})
	return file_sub_msg_proto_rawDescData
}

var file_sub_msg_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_sub_msg_proto_goTypes = []interface{}{
	(*GetSubMessageReq)(nil),   // 0: api.subMessage.v1.GetSubMessageReq
	(*GetSubMessageReply)(nil), // 1: api.subMessage.v1.GetSubMessageReply
}
var file_sub_msg_proto_depIdxs = []int32{
	0, // 0: api.subMessage.v1.GetSubMessageService.GetSubMessage:input_type -> api.subMessage.v1.GetSubMessageReq
	1, // 1: api.subMessage.v1.GetSubMessageService.GetSubMessage:output_type -> api.subMessage.v1.GetSubMessageReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sub_msg_proto_init() }
func file_sub_msg_proto_init() {
	if File_sub_msg_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sub_msg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSubMessageReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sub_msg_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSubMessageReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sub_msg_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sub_msg_proto_goTypes,
		DependencyIndexes: file_sub_msg_proto_depIdxs,
		MessageInfos:      file_sub_msg_proto_msgTypes,
	}.Build()
	File_sub_msg_proto = out.File
	file_sub_msg_proto_rawDesc = nil
	file_sub_msg_proto_goTypes = nil
	file_sub_msg_proto_depIdxs = nil
}
